/* Trattoria D'Elite - PERFIS SOMENTE PARA DEMONSTRACAO
 * GitHub Pages nao oferece autenticacao real. Nunca utilizar senhas pessoais.
 * Na demo, codigo de acesso guardado exclusivamente como derivacao PBKDF2 com salt
 * dentro do navegador. Dados nao sao enviados a servidores nem compartilhados.
 * Protecao real exige API segura com HTTPS, banco e sessao autenticada.
 */
(async function(){
"use strict";
const ACCOUNTS="trattoriaPerfisDemoV2", SESSION="trattoriaSessaoDemoV2";
const ITER=220000, MIN_ACCESS=8;
const $=id=>document.getElementById(id);
const safe=(()=>{try{localStorage.setItem("__tdtest","ok");localStorage.removeItem("__tdtest");return !!crypto?.subtle}catch{return false}})();
const read=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem(key));return v===null?fallback:v}catch{return fallback}};
function accounts(){const v=read(ACCOUNTS,[]);return Array.isArray(v)?v:[]}
function key(s){return String(s||"").trim().toLocaleLowerCase("pt-BR")}
function msg(message,error=false){const m=$("accountMessage");if(!m)return;m.textContent=message;m.className="account-msg "+(error?"error":"success")}
const hex=a=>Array.from(new Uint8Array(a)).map(b=>b.toString(16).padStart(2,"0")).join("");
function unhex(str){const res=new Uint8Array(str.length/2);for(let i=0;i<res.length;i++)res[i]=parseInt(str.substring(i*2,i*2+2),16);return res}
async function hash(password,salt){const raw=new TextEncoder().encode(password);const base=await crypto.subtle.importKey("raw",raw,"PBKDF2",false,["deriveBits"]);const result=await crypto.subtle.deriveBits({name:"PBKDF2",salt:unhex(salt),iterations:ITER,hash:"SHA-256"},base,256);return hex(result)}
async function createRecord(name,email,access){const salt=hex(crypto.getRandomValues(new Uint8Array(16)));return {id:crypto.randomUUID(),name,email:key(email),salt,verifier:await hash(access,salt),createdAt:new Date().toISOString()}}
function requireBrowser(){if(safe)return true;msg("Este navegador nao permite salvar perfis de teste com seguranca. Tente usar HTTPS ou localhost.",true);return false}
function session(){const id=localStorage.getItem(SESSION);return accounts().find(u=>u.id===id)||null}
function saveAll(a){localStorage.setItem(ACCOUNTS,JSON.stringify(a))}
async function migrate(){let raw=null;try{raw=JSON.parse(localStorage.getItem("usuarioTrattorito")||"null")}catch{}if(!raw||!raw.email||!raw.senha||!safe)return;try{const list=accounts(),email=key(raw.email);let record=list.find(x=>x.email===email);if(!record){record=await createRecord(String(raw.nome||"Cliente").trim(),email,String(raw.senha));list.push(record);saveAll(list)}if(localStorage.getItem("usuarioLogado")==="true")localStorage.setItem(SESSION,record.id);localStorage.removeItem("usuarioTrattorito");localStorage.removeItem("usuarioLogado")}catch(e){console.warn("Migracao antiga nao concluida.",e)}}
function toggleReveal(){document.querySelectorAll("[data-reveal]").forEach(b=>b.addEventListener("click",()=>{const ids=b.dataset.reveal.split(",");const targets=ids.map(id=>$(id)).filter(Boolean),show=targets.some(i=>i.type==="password");targets.forEach(i=>i.type=show?"text":"password");b.textContent=show?"Ocultar":"Mostrar";b.setAttribute("aria-pressed",String(show))}))}
function register(){const form=$("accountRegister");if(!form)return;form.addEventListener("submit",async e=>{e.preventDefault();if(!requireBrowser())return;const name=$("nome").value.trim().replace(/\s+/g," "),email=key($("email").value),pass=$("senha").value,confirm=$("confirmarSenha").value;if(name.length<2||name.length>80)return msg("Digite um nome de 2 a 80 caracteres.",true);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>160)return msg("Informe um e-mail valido para o teste.",true);if(pass.length<MIN_ACCESS||pass.length>64)return msg("O acesso de teste deve ter entre 8 e 64 caracteres.",true);if(pass!==confirm)return msg("Os acessos digitados nao sao iguais.",true);if(accounts().some(x=>x.email===email))return msg("Este e-mail ja tem perfil neste navegador. Clique em Entrar.",true);const b=form.querySelector('button[type="submit"]');b.disabled=true;try{const p=await createRecord(name,email,pass);saveAll([...accounts(),p]);sessionStorage.setItem("trattoriaCadastroPronto","1");msg("Perfil demonstrativo salvo! Abrindo a tela para entrar...");setTimeout(()=>location.assign("login.html"),800)}catch(ex){console.error(ex);msg("Nao foi possivel salvar. Verifique o navegador.",true)}finally{b.disabled=false}})}
function login(){const form=$("accountLogin");if(!form)return;try{if(sessionStorage.getItem("trattoriaCadastroPronto")){msg("Cadastro salvo. Agora entre usando seu e-mail e acesso de teste.");sessionStorage.removeItem("trattoriaCadastroPronto")}}catch{}form.addEventListener("submit",async e=>{e.preventDefault();if(!requireBrowser())return;const email=key($("email").value),pass=$("senha").value,record=accounts().find(x=>x.email===email);const b=form.querySelector('button[type="submit"]');b.disabled=true;try{let valid=false;if(record&&record.salt&&record.verifier)valid=await hash(pass,record.salt)===record.verifier;if(!valid)return msg("E-mail ou acesso incorretos neste navegador.",true);localStorage.setItem(SESSION,record.id);msg("Bem-vindo de volta!");location.assign("perfil.html")}catch(ex){console.error(ex);msg("Nao foi possivel entrar neste navegador.",true)}finally{b.disabled=false}})}
function profile(){const page=$("accountProfile");if(!page)return;const u=session();if(!u){location.replace("login.html");return}const first=(u.name.split(/\s+/).filter(Boolean)[0]||"Cliente");$("perfilNome").textContent=u.name;$("perfilEmail").textContent=u.email;$("perfilAvatar").textContent=first.slice(0,1).toLocaleUpperCase("pt-BR");$("nome").value=u.name;$("perfilInicio").textContent=u.createdAt?new Date(u.createdAt).toLocaleDateString("pt-BR"):"Data indisponivel";$("perfilFavoritos").textContent=read("eliteFavoritos",[]).length;$("perfilPedidos").textContent=read("trattoritoPedidos",[]).length;$("accountProfileForm").addEventListener("submit",e=>{e.preventDefault();const name=$("nome").value.trim().replace(/\s+/g," ");if(name.length<2||name.length>80)return msg("Digite um nome de 2 a 80 caracteres.",true);const a=accounts(),found=a.find(x=>x.id===u.id);if(!found)return msg("Perfil nao encontrado neste navegador.",true);found.name=name;try{saveAll(a);$("perfilNome").textContent=name;$("perfilAvatar").textContent=name[0].toLocaleUpperCase("pt-BR");msg("Nome atualizado neste navegador.")}catch{msg("Nao foi possivel salvar o nome.",true)}});$("logout").addEventListener("click",()=>{localStorage.removeItem(SESSION);location.assign("login.html")});$("removeProfile").addEventListener("click",()=>{if(!window.confirm("Excluir somente este perfil demonstrativo deste navegador? Essa acao nao pode ser desfeita."))return;saveAll(accounts().filter(x=>x.id!==u.id));localStorage.removeItem(SESSION);location.assign("cadastro.html")})}
function nav(){const u=session();const a=$("account-entry"),hero=$("account-hero-link");if(a){a.textContent=u?"👤 Meu perfil":"👤 Entrar no perfil";a.href=u?"perfil.html":"login.html"}if(hero){hero.textContent=u?"👤 Abrir meu perfil":"👤 Entrar no meu perfil";hero.href=u?"perfil.html":"login.html"}}
await migrate();
nav();toggleReveal();register();login();profile();
})();
