/* Trattoria D'Elite - 8 melhorias, camada reversivel. Cupons e pontos: demonstracao. */
(() => {
"use strict";
const page=location.pathname.split("/").pop()||"index.html";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const fmt=n=>(Number(n)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();
const cartKey="carrinhoCantina", orderKey="trattoritoPedidos";
const localHost=["localhost","127.0.0.1"].includes(location.hostname);
const routes={"Pratos Principais":"pratos.html","Sobremesas":"sobremesas.html","Bebidas":"bebidas.html"};
const names={
"Pratos Principais":["Spaghetti alla Norma","Spaghetti alla Carbonara","Ravioli al Pesto","Spaghetti Cacio e Pepe","Gnocchi alla Sorrentina","Fettuccine ao Pesto com Camarões","Pizza ai Funghi","Ravioli de Queijo ao Molho Cremoso","Risoto de Funghi","Pizza Margherita","Receita de Ensalada de Pasta con Pollo","Filé Mignon ao Molho de Vinho Tinto","Pollo al limone con rosmarino","Beef Stew","Beef carpaccio with arugula and parmesan","Carpaccio di Manzo","Risoto Cremoso de Cogumelos","Fettuccine ao Molho Cremoso com Parmesão","Fettuccine ao molho Pesto","Ravioli de Limão siciliano","Salada Caesar com Camarão Grelhado","Salada Caprese","Caponata de Berinjela","Burrata com Tomates-Cereja","Creme de Abóbora","Sopa Cremosa de Abacate com Torradas"],
"Sobremesas":["Cannoli de Limão Siciliano","Panna Cotta de Maracujá","Cannoli de Pistache","Panna Cotta de Frutas Vermelhas","Tiramisù","Torta de Frutas Vermelhas","Panna Cotta de Café","Torta de Maracujá","Classic Sicilian Cannoli","Torta Caprese","Sfogliatella"],
"Bebidas":["Limonada Rosa","Limonada"]
};
const catalog=Object.entries(names).flatMap(([categoria,list])=>list.map(nome=>({nome,categoria,href:routes[categoria]})));
let banco=[];
function read(k){try{const x=JSON.parse(localStorage.getItem(k)||"[]");return Array.isArray(x)?x:[]}catch{return []}}
function save(k,x){try{localStorage.setItem(k,JSON.stringify(x));return true}catch{alert("Nao foi possivel salvar neste navegador.");return false}}
function el(tag,cls,txt){const e=document.createElement(tag);if(cls)e.className=cls;if(txt!==undefined)e.textContent=txt;return e}
function btn(txt,cls="m8-btn"){const e=el("button",cls,txt);e.type="button";return e}
function alertUI(txt){let e=$("#m8-notice");if(!e){e=el("div","m8-notice");e.id="m8-notice";e.setAttribute("role","status");document.body.append(e)}e.textContent=txt;e.classList.add("m8-visible");clearTimeout(alertUI.timer);alertUI.timer=setTimeout(()=>e.classList.remove("m8-visible"),3600)}
function numberFromBR(s){return Number(String(s||"").replace(/[^\d,.]/g,"").replace(/\./g,"").replace(",","."))||0}
function addCart(p,note,qty){if(!(p.preco>0)||!p.nome)return alertUI("Produto indisponivel.");const c=read(cartKey);let x=c.find(v=>v.nome===p.nome&&String(v.observacao||"")===note&&!v.adicionais);if(x)x.quantidade=Math.min(99,(Number(x.quantidade)||0)+qty);else c.push({nome:p.nome,preco:p.preco,imagem:p.imagem,quantidade:qty,observacao:note,adicionais:""});if(save(cartKey,c)){badge();alertUI("Adicionado ao carrinho: "+p.nome)}}
function badge(){const b=$("#m8-float-count");if(b)b.textContent=read(cartKey).reduce((n,p)=>n+(Number(p.quantidade)||0),0)}
function cardData(card){return {nome:$("h3",card)?.textContent?.trim()||"",descricao:$(".menu-card-body p",card)?.textContent?.trim()||"",preco:numberFromBR($(".price",card)?.textContent),imagem:$("img",card)?.getAttribute("src")||""}}
function suggestions(root,value){root.replaceChildren();const q=norm(value);if(q.length<2)return;const matches=[...banco,...catalog].filter(x=>norm(x.nome+" "+x.categoria+" "+(x.descricao||"")).includes(q));const seen=new Set();for(const p of matches){const k=p.categoria+p.nome;if(seen.has(k)||seen.size>=6)continue;seen.add(k);const a=el("a","m8-suggestion",p.nome+" · "+p.categoria);a.href=(routes[p.categoria]||p.href||"pratos.html")+"?busca="+encodeURIComponent(p.nome);root.append(a)}if(!seen.size)root.append(el("p","m8-small","Nenhum resultado. Experimente outro nome."))}
function searchUI(root,isHome){const wrap=el("section",isHome?"m8-home-search":"m8-menu-search");const heading=el("h2","",isHome?"Encontre seu prato favorito":"Busca inteligente do cardapio");const input=el("input");input.type="search";input.placeholder="Pizza, carbonara, molho, sobremesa...";input.setAttribute("aria-label","Pesquisar pratos e ingredientes");const result=el("div","m8-results"),info=el("p","m8-small", "Pesquise por nome, ingrediente ou categoria.");wrap.append(heading,input,info,result);root.insertAdjacentElement("afterend",wrap);const run=()=>{if(!isHome){let count=0;$$(".menu-card").forEach(c=>{const show=!norm(input.value)||norm(c.textContent).includes(norm(input.value));c.style.display=show?"":"none";if(show)count++});info.textContent=count+" produtos nesta categoria. Outras categorias abaixo."}suggestions(result,input.value)};input.addEventListener("input",run);input.addEventListener("keydown",e=>{if(e.key==="Escape"){input.value="";run()}});const q=new URLSearchParams(location.search).get("busca");if(q){input.value=q;run()}return wrap}
function initHome(){if(page!=="index.html")return;const header=$(".topbar");if(!header)return;document.body.classList.add("m8-home");const hero=el("section","m8-spotlight");hero.innerHTML='<div class="m8-spotlight-inner"><span class="m8-kicker">TRATTORIA D’ELITE · CUCINA ITALIANA</span><h2>A Italia no seu proximo pedido.</h2><p>Sabores italianos, receitas especiais e uma experiencia elegante do inicio ao fim.</p><div class="m8-actions"><a class="m8-btn" href="pratos.html">Explorar cardapio →</a><a class="m8-btn m8-outline" href="sobremesas.html">Ver sobremesas</a></div></div><span class="m8-spotlight-label">Selecao da casa · Pizza Margherita</span>';header.insertAdjacentElement("afterend",hero);searchUI(hero,true);const after=$(".elite-section");if(after)recommend(after)}
function initPersonal(){if(!["pratos.html","sobremesas.html","bebidas.html"].includes(page))return;document.addEventListener("click",e=>{const b=e.target.closest(".elite-small-btn");if(!b||!norm(b.textContent).includes("personalizar"))return;const card=b.closest(".menu-card");if(!card)return;e.preventDefault();e.stopImmediatePropagation();e.stopPropagation();openDialog(cardData(card))},true)}
function openDialog(p){let d=$("#m8-personalizar");if(!d){d=el("dialog","m8-dialog");d.id="m8-personalizar";d.innerHTML='<form class="m8-dialog-layout"><div class="m8-photo"><img id="m8-photo" alt=""></div><div class="m8-dialog-body"><button type="button" class="m8-x" id="m8-x" aria-label="Fechar">×</button><span class="m8-kicker">MONTE SEU PEDIDO</span><h2 id="m8-name"></h2><p id="m8-desc"></p><strong id="m8-price"></strong><label for="m8-qty">Quantidade</label><input id="m8-qty" type="number" min="1" max="20" value="1" required><label for="m8-note">Observacoes para a cozinha</label><textarea id="m8-note" maxlength="180" rows="3" placeholder="Ex.: sem cebola, molho separado"></textarea><small>Sem adicionais pagos. O servidor calcula o valor oficial do produto.</small><button type="submit" class="m8-btn">Adicionar ao carrinho</button></div></form>';document.body.append(d);$("#m8-x",d).onclick=()=>d.close();d.addEventListener("click",e=>{if(e.target===d)d.close()})}$("#m8-photo",d).src=p.imagem;$("#m8-photo",d).alt=p.nome;$("#m8-name",d).textContent=p.nome;$("#m8-desc",d).textContent=p.descricao;$("#m8-price",d).textContent=fmt(p.preco);$("#m8-qty",d).value=1;$("#m8-note",d).value="";$("form",d).onsubmit=e=>{e.preventDefault();addCart(p,$("#m8-note",d).value.trim().slice(0,180),Math.max(1,Math.min(20,Math.floor(Number($("#m8-qty",d).value)||1))));d.close()};if(typeof d.showModal==="function")d.showModal();else d.setAttribute("open","")}
function initCart(){if(page!=="carrinho.html")return;const root=$("#cart");if(!root)return;const p=el("section","m8-cart-box");p.innerHTML='<span class="m8-kicker">CARRINHO INTELIGENTE</span><h2>Seu pedido do seu jeito</h2><p>Ajuste as quantidades com os botoes + e − e teste os beneficios ilustrativos.</p><div class="m8-progress-label" id="m8-progress-label"></div><div class="m8-progress"><span id="m8-progress-bar"></span></div><div class="m8-coupons"><input id="m8-coupon" aria-label="Cupom demonstrativo" maxlength="20" placeholder="Cupom: ITALIA10"><button type="button" class="m8-btn" id="m8-apply">Aplicar</button><button type="button" class="m8-btn m8-outline" id="m8-clear">Limpar</button></div><p id="m8-discount" class="m8-small"></p><p class="m8-warning">Cupons e beneficios sao somente simulacoes. O pagamento demonstrativo e a API continuam usando os valores oficiais do SQL Server.</p>';root.insertAdjacentElement("afterend",p);const decorate=()=>{$$(".cart-table tr",root).slice(1).forEach((tr,i)=>{const cell=tr.children[1];if(!cell||$(".m8-qty-controls",cell))return;const num=cell.textContent.trim();cell.replaceChildren();const group=el("div","m8-qty-controls");const m=btn("−","m8-qty-btn");m.dataset.delta="-1";m.dataset.index=i;const plus=btn("+","m8-qty-btn");plus.dataset.delta="1";plus.dataset.index=i;group.append(m,el("strong","",num),plus);cell.append(group)})};root.addEventListener("click",e=>{const b=e.target.closest("[data-delta]");if(!b)return;const idx=Number(b.dataset.index),c=read(cartKey);if(!c[idx])return;const next=(Number(c[idx].quantidade)||1)+Number(b.dataset.delta);if(next<=0)c.splice(idx,1);else c[idx].quantidade=Math.min(99,next);if(save(cartKey,c))location.reload()});const refresh=()=>{const total=read(cartKey).reduce((a,x)=>a+(Number(x.preco)||0)*(Number(x.quantidade)||1),0);$("#m8-progress-label").textContent=total>=150?"Meta visual de R$ 150 atingida!":"Meta visual: faltam "+fmt(150-total)+" para R$ 150";$("#m8-progress-bar").style.width=Math.min(100,total/150*100)+"%";const code=localStorage.getItem("m8CupomDemo")||"";const rate=code==="ITALIA10"?.1:code==="BEMVINDO5"?.05:0;$("#m8-discount").textContent=rate?"Cupom "+code+": desconto ilustrativo "+fmt(total*rate)+". Total ilustrativo "+fmt(total*(1-rate))+".":"Cupons de teste: ITALIA10 (10%) e BEMVINDO5 (5%)."};$("#m8-apply").onclick=()=>{const code=$("#m8-coupon").value.toUpperCase().trim();if(!["ITALIA10","BEMVINDO5"].includes(code))return alertUI("Cupom de teste invalido.");localStorage.setItem("m8CupomDemo",code);refresh();alertUI("Cupom demonstrativo selecionado.")};$("#m8-clear").onclick=()=>{localStorage.removeItem("m8CupomDemo");$("#m8-coupon").value="";refresh()};$("#m8-coupon").value=localStorage.getItem("m8CupomDemo")||"";decorate();refresh();recommend(p);loyalty(p)}
function loyalty(root){const orders=read(orderKey);const ids=new Set();let total=0;for(const p of orders){if(!p||!p.id||ids.has(p.id))continue;ids.add(p.id);total+=Math.floor(Math.max(0,Number(p.total)||0)/10)}const e=el("section","m8-loyalty");e.innerHTML='<div><span class="m8-kicker">CLUBE D’ELITE · DEMONSTRACAO</span><h2>Seus sabores rendem pontos</h2><p>1 ponto ilustrativo a cada R$ 10 em pedidos deste navegador. Nao representam beneficios reais.</p></div><div class="m8-loyalty-count"><strong></strong><span>pontos demonstrativos</span></div>';$(".m8-loyalty-count strong",e).textContent=total;root.append(e)}
function initLoyalty(){if(page==="index.html"){const mount=$(".elite-container");if(mount)loyalty(mount)}}
function initTrack(){if(page!=="pedido.html")return;const status=$("#orderStatus"),timeline=$("#timeline");if(!status||!timeline)return;const p=el("section","m8-tracker");p.innerHTML='<div class="m8-tracker-head"><span class="m8-kicker">ACOMPANHAMENTO</span><button type="button" class="m8-btn m8-outline" id="m8-refresh">Atualizar status</button></div><div class="m8-tracker-steps"></div><p class="m8-small" id="m8-tracker-message"></p>';timeline.insertAdjacentElement("beforebegin",p);for(const label of ["Recebido","Em preparo","A caminho","Entregue"])$(".m8-tracker-steps",p).append(el("div","m8-tracker-step",label));const paint=()=>{const s=norm(status.textContent);const i=s.includes("preparo")?1:s.includes("entregue")?3:s.includes("entrega")||s.includes("caminho")?2:0;$$(".m8-tracker-step",p).forEach((x,j)=>{x.classList.toggle("m8-past",j<i);x.classList.toggle("m8-current",j===i)})};new MutationObserver(paint).observe(status,{childList:true,subtree:true,characterData:true});paint();const b=$("#m8-refresh");$("#m8-tracker-message").textContent=localHost?"Consulte o status atualizado pela API local.":"Nesta pagina publica, os pedidos demonstrativos ficam no navegador. A API SQL e somente local.";b.disabled=!localHost;b.onclick=async()=>{if(!localHost)return;const number=($("#orderNumber")?.textContent||"").match(/TD-[A-Z0-9-]+/i)?.[0];if(!number)return alertUI("Selecione um pedido.");b.disabled=true;try{const r=await fetch("/api/pedidos/"+encodeURIComponent(number));if(!r.ok)throw new Error(r.status);const p=await r.json();const data=read(orderKey),x=data.find(y=>y.id===p.numero);if(x){x.status=p.status;x.total=p.total;x.createdAt=p.dataPedido;save(orderKey,data)}alertUI("Status consultado no SQL Server.");setTimeout(()=>location.reload(),400)}catch{alertUI("Nao foi possivel consultar o servidor local.")}finally{b.disabled=false}};const old=$(".demo-actions");if(old)old.insertAdjacentElement("beforebegin",el("p","m8-warning","Os botoes de simulacao existentes nao alteram o SQL Server."))}
function initMobile(){document.body.classList.add("m8-responsive");if(["carrinho.html","pagamento.html"].includes(page))return;const a=el("a","m8-floating");a.href="carrinho.html";a.setAttribute("aria-label","Abrir carrinho");a.innerHTML='<span>🛒 Meu carrinho</span><strong id="m8-float-count">0</strong>';document.body.append(a);badge();document.addEventListener("click",()=>setTimeout(badge,80));window.addEventListener("storage",badge)}
function initSearch(){if(!["pratos.html","sobremesas.html","bebidas.html"].includes(page))return;const nav=$(".category-nav");if(!nav)return;searchUI(nav,false);if(localHost)fetch("/api/produtos").then(r=>r.ok?r.json():[]).then(rows=>{if(Array.isArray(rows))banco=rows.map(p=>({nome:p.nome??p.Nome,descricao:p.descricao??p.Descricao,categoria:p.categoria??p.Categoria}))}).catch(()=>{});const main=$("main");if(main)recommend(main)}
function recommend(root){if(!root||$(".m8-recommend"))return;const c=norm(read(cartKey).map(x=>x.nome).join(" ")),f=norm(read("eliteFavoritos").map(x=>x.nome).join(" "));const dessert=c.includes("pizza")||c.includes("spaghetti")||f.includes("pizza");const products=dessert?[["Tiramisù","sobremesas.html?busca=Tiramis%C3%B9","imagens/sobremesas/tiramisu.webp"],["Limonada Rosa","bebidas.html?busca=Limonada%20Rosa",""],["Risoto de Funghi","pratos.html?busca=Risoto%20de%20Funghi","imagens/pratos/risoto-funghi.webp"]]:[["Pizza Margherita","pratos.html?busca=Pizza%20Margherita","imagens/pratos/pizza-margherita.webp"],["Risoto de Funghi","pratos.html?busca=Risoto%20de%20Funghi","imagens/pratos/risoto-funghi.webp"],["Tiramisù","sobremesas.html?busca=Tiramis%C3%B9","imagens/sobremesas/tiramisu.webp"]];const section=el("section","m8-recommend");section.append(el("span","m8-kicker","ESCOLHAS PARA VOCE"),el("h2","","Talvez voce tambem goste"),el("p","m8-small","Sugestoes de pratos inspiradas no seu carrinho e favoritos deste navegador."));const grid=el("div","m8-recommend-grid");for(const [nome,href,img] of products){const a=el("a","m8-rec-item");a.href=href;if(img){const image=el("img");image.src=img;image.loading="lazy";image.alt="";a.append(image)}else a.append(el("span","m8-rec-icon","🍋"));a.append(el("strong","",nome),el("small","","Ver no cardapio →"));grid.append(a)}section.append(grid);root.insertAdjacentElement("afterend",section)}
function init(){initHome();initPersonal();initCart();initLoyalty();initTrack();initMobile();initSearch();console.info("Trattoria D'Elite: 8 melhorias carregadas; cupons/pontos demonstrativos.")}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();