/* Trattoria D'Elite | Central de recursos 1-48.
 * Recursos administrativos desta pagina sao demonstracoes LOCAIS.
 * Nunca representam confirmacao da cozinha nem dados persistidos no servidor.
 */
(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const fmt=n=>(Number(n)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const safe=s=>String(s??"").trim().slice(0,180);
const read=(key,def=[])=>{try{let x=JSON.parse(localStorage.getItem(key)||"null");return x??def}catch{return def}};
const write=(key,v)=>{try{localStorage.setItem(key,JSON.stringify(v));return true}catch{alert("Armazenamento deste navegador indisponivel.");return false}};
const by=id=>document.getElementById(id);
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const notify=s=>{const e=by("t48-message")||document.body.appendChild(node("div","t48-toast"));e.id="t48-message";e.setAttribute("role","status");e.textContent=s;e.classList.add("visible");clearTimeout(notify.timer);notify.timer=setTimeout(()=>e.classList.remove("visible"),3300)};
const fields={
"1":["Página inicial premium","index.html","Pronto"],
"2":["Personalização dos pratos","pratos.html","Pronto"],
"3":["Carrinho inteligente","carrinho.html","Pronto"],
"4":["Programa de fidelidade","perfil.html","Demo"],
"5":["Acompanhamento visual","pedido.html","Demo"],
"6":["Versão mobile","index.html","Pronto"],
"7":["Busca inteligente","pratos.html","Pronto"],
"8":["Recomendações","pratos.html","Pronto"],
"9":["Reserva de mesas","laboratorio.html#reservas","Demo"],
"10":["Pedir novamente","laboratorio.html#pedir-novamente","Demo"],
"11":["Painel administrativo","painel.html","Demo"],
"12":["Painel da cozinha","laboratorio.html#cozinha","Demo"],
"13":["Controle de estoque","laboratorio.html#estoque","Demo"],
"14":["Relatórios e gráficos","laboratorio.html#relatorios","Demo"],
"15":["Assistente de dúvidas","laboratorio.html#assistente","Demo"],
"16":["Site instalável (PWA)","laboratorio.html#instalavel","Pronto"],
"17":["Modo escuro","laboratorio.html#aparencia","Pronto"],
"18":["Central de notificações","laboratorio.html#notificacoes","Demo"],
"19":["Perfil do cliente","perfil.html","Demo"],
"20":["Avaliações com fotos","avaliacoes.html","Pendente"],
"21":["Menu do dia","laboratorio.html#promocoes","Demo"],
"22":["Promoções programadas","laboratorio.html#promocoes","Demo"],
"23":["QR Code do cardápio","laboratorio.html#qrcode","Pronto"],
"24":["Lista de ingredientes","laboratorio.html#informacoes","Informativo"],
"25":["Comparador de pratos","laboratorio.html#comparador","Pronto"],
"26":["Acessibilidade","laboratorio.html#aparencia","Pronto"],
"27":["Monte seu próprio prato","laboratorio.html#montar-prato","Demo"],
"28":["Agendar pedidos","laboratorio.html#agendamentos","Demo"],
"29":["Informações alimentares","laboratorio.html#informacoes","Informativo"],
"30":["Comprovante em PDF","laboratorio.html#comprovante","Demo"],
"31":["Caixa digital (PDV)","laboratorio.html#pdv","Demo"],
"32":["Sistema de funcionários","laboratorio.html#infra","Pendente"],
"33":["Impressão de comandas","laboratorio.html#cozinha","Demo"],
"34":["Cronômetro de preparo","laboratorio.html#cozinha","Demo"],
"35":["Aberto ou fechado","laboratorio.html#funcionamento","Demo"],
"36":["Cancelamento de pedidos","laboratorio.html#cancelamentos","Demo"],
"37":["Central de ajuda","laboratorio.html#assistente","Demo"],
"38":["Cardápio sazonal","laboratorio.html#promocoes","Demo"],
"39":["Histórico de alterações","laboratorio.html#historico","Demo"],
"40":["Painel de entregadores","laboratorio.html#entregas","Demo"],
"41":["Lista de espera","laboratorio.html#fila","Demo"],
"42":["Eventos e encomendas","laboratorio.html#eventos","Demo"],
"43":["Português, inglês e italiano","laboratorio.html#idiomas","Parcial"],
"44":["Galeria do restaurante","laboratorio.html#galeria","Pronto"],
"45":["Site mais rápido","laboratorio.html#instalavel","Parcial"],
"46":["SEO para Google","laboratorio.html#instalavel","Pronto"],
"47":["Backup do sistema","laboratorio.html#infra","Parcial"],
"48":["Proteção contra pedidos duplicados","laboratorio.html#infra","Pendente"]
};
const products=[
{n:"Pizza Margherita",p:49.9,img:"imagens/pratos/pizza-margherita.webp",c:"Prato principal",ing:"Tomate, mozzarella, manjericão e azeite"},
{n:"Spaghetti alla Carbonara",p:49.9,img:"imagens/pratos/spaghetti-carbonara.webp",c:"Prato principal",ing:"Espaguete, queijo, ovos, pancetta e pimenta"},
{n:"Risoto de Funghi",p:79.9,img:"imagens/pratos/risoto-funghi.webp",c:"Prato principal",ing:"Arroz para risoto, funghi, queijo e ervas"},
{n:"Salada Caprese",p:29.9,img:"imagens/pratos/salada-caprese.webp",c:"Prato principal",ing:"Tomate, mozzarella, manjericão e azeite"},
{n:"Tiramisù",p:32.9,img:"imagens/sobremesas/tiramisu.webp",c:"Sobremesa",ing:"Mascarpone, café, biscoito e cacau"},
{n:"Panna Cotta de Maracujá",p:28.9,img:"imagens/sobremesas/panna-maracuja.webp",c:"Sobremesa",ing:"Creme e maracujá"},
{n:"Limonada",p:19.99,img:"",c:"Bebida",ing:"Limão e água"}
];
const sections=[
["reservas","Reserva de mesas","Solicitações apenas neste navegador; não reservam uma mesa real."],
["pedir-novamente","Pedir novamente","Copie para o carrinho os itens de pedidos de demonstração anteriores."],
["cozinha","Cozinha e comandas","Pedidos, timer e impressão local, sem alterar o SQL Server."],
["estoque","Estoque demonstrativo","Simule disponibilidade de produtos neste navegador."],
["relatorios","Relatórios e gráficos","Indicadores dos pedidos demonstrativos salvos neste navegador."],
["assistente","Ajuda e assistente","Respostas fixas para dúvidas frequentes; não é um atendente real."],
["instalavel","Aplicativo e desempenho","Instalação no celular e melhorias de carregamento de páginas estáticas."],
["aparencia","Aparência e acessibilidade","Tema escuro, navegação e tamanho da leitura."],
["notificacoes","Central de notificações","Recados ilustrativos deste navegador, não notificações da cozinha."],
["promocoes","Menu do dia e promoções","Ofertas e datas ilustrativas; descontos não são enviados ao SQL Server."],
["qrcode","Cardápio por QR Code","Compartilhe o link público do cardápio."],
["informacoes","Ingredientes e informações alimentares","Descrições informativas; confirme ingredientes e alérgenos com a cozinha."],
["comparador","Comparar pratos","Compare ingredientes e preços informativos dos pratos."],
["montar-prato","Monte seu prato","Escolha um prato cadastrado e adicione observações sem alterar seu preço."],
["agendamentos","Agendamento de pedidos","Agenda demonstrativa, sem promessa de entrega ou reserva no servidor."],
["comprovante","Comprovante para impressão","Use a opção Imprimir / Salvar como PDF do navegador."],
["pdv","Caixa digital demonstrativo","Pedidos locais de caixa, sem registrar vendas nem pagamentos no banco."],
["funcionamento","Restaurante aberto ou fechado","Indicador local de teste; não bloqueia pedidos reais."],
["cancelamentos","Cancelamento demonstrativo","Altera apenas pedidos de teste salvos no navegador."],
["historico","Histórico de alterações","Registro de ações realizadas nesta central demonstrativa."],
["entregas","Painel de entregadores","Atribuição ilustrativa, sem rastreamento ou entregas reais."],
["fila","Lista de espera","Senhas de espera locais, sem coleta de dados pessoais."],
["eventos","Eventos e encomendas","Solicitações ilustrativas, não enviadas ao restaurante."],
["idiomas","Idiomas","Controles da central em português, inglês ou italiano."],
["galeria","Galeria dos pratos","Fotos existentes no cardápio."],
["infra","Recursos que precisam de servidor","Funcionalidades profissionais ainda não ligadas à API segura."]
];
const steps=(root)=>{root.append(node("p","t48-disclaimer","ATENÇÃO: Este painel reúne recursos de demonstração. Reservas, status, estoque, entregas, descontos e pedidos locais aqui não são confirmações reais do restaurante nem operações no SQL Server."))};
function options(select,items){for(const [val,label] of items){const opt=node("option","",label);opt.value=val;select.append(opt)}}
function makeForm(id,content){const f=node("form","t48-form");f.id=id;f.innerHTML=content;return f}
function row(label,value){const tr=node("div","t48-row");tr.append(node("span","",label),node("strong","",value));return tr}
function log(action){const items=read("t48Audit");items.unshift({date:new Date().toISOString(),action:safe(action)});write("t48Audit",items.slice(0,50))}
function mount(id){return by("t48-"+id)}
function panel(id,desc,action){const el=mount(id);el.innerHTML="";el.append(node("p","t48-info",desc));if(action)action(el)}
function printMode(title,lines){const root=by("t48-print");root.replaceChildren();root.append(node("h1","", "TRATTORIA D'ELITE"),node("h2","",title),node("p","",new Date().toLocaleString("pt-BR")));for(const [a,b] of lines)root.append(row(a,b));root.removeAttribute("hidden");document.body.classList.add("t48-printing");window.print();setTimeout(()=>{document.body.classList.remove("t48-printing");root.hidden=true},1200)}
function initPortal(){const root=by("portalApp");if(!root)return;const nav=node("div","t48-filters");for(const x of ["Todos","Pronto","Demo","Pendente"]){const b=node("button","t48-chip",x);b.type="button";b.onclick=()=>{ $$(".t48-chip",nav).forEach(c=>c.classList.toggle("active",c===b));$$(".t48-feature",root).forEach(c=>c.hidden=x!=="Todos"&&c.dataset.status!==x)};nav.append(b)}$(".t48-chip",nav).click();root.append(nav);const grid=node("div","t48-feature-grid");for(const [number,[title,href,status]] of Object.entries(fields)){const card=node("article","t48-feature");card.dataset.status=status;const top=node("div","t48-feature-top");top.append(node("span","t48-number",number.padStart(2,"0")),node("span","t48-status "+(status==="Pendente"?"pending":status==="Pronto"?"ready":"demo"),status));card.append(top,node("h3","",title));const link=node("a","t48-link",status==="Pendente"?"Ver requisitos →":"Abrir recurso →");link.href=href;card.append(link);grid.append(card)}root.append(grid);root.insertAdjacentElement("afterend",node("p","t48-footnote","Funções demonstrativas só usam este navegador. Para persistência entre dispositivos é necessária uma API segura."))}
function initLab(){const root=by("labApp");if(!root)return;steps(root);const nav=node("nav","t48-lab-nav");nav.setAttribute("aria-label","Ir para recurso");const wrap=node("div","t48-sections");for(const [id,title,description] of sections){const a=node("a","",title);a.href="#"+id;nav.append(a);const section=node("section","t48-module");section.id=id;section.append(node("h2","",title));const inner=node("div","t48-module-body");inner.id="t48-"+id;section.append(inner);wrap.append(section)}root.append(nav,wrap);bindModules()}
function initReservation(){panel("reservas","Informe apenas um apelido. Esta é uma lista de testes e não bloqueia mesas.",root=>{const form=makeForm("t48-resform",'<label>Apelido<input name="nick" maxlength="30" required placeholder="Ex.: Mesa da Ana"></label><label>Data<input name="date" type="date" required></label><label>Horário<input name="time" type="time" required></label><label>Pessoas<input name="count" type="number" min="1" max="12" value="2" required></label><button type="submit">Salvar reserva de teste</button>');root.append(form);const list=node("div","t48-list");root.append(list);function draw(){list.replaceChildren();const reservations=read("t48Reservations");if(!reservations.length)list.append(node("p","t48-muted","Nenhuma reserva de teste."));for(const r of reservations){const a=row(r.nick,r.date+" às "+r.time+" · "+r.count+" pessoas");const b=node("button","t48-small","Excluir");b.onclick=()=>{write("t48Reservations",read("t48Reservations").filter(x=>x.id!==r.id));log("Reserva de teste excluída");draw()};a.append(b);list.append(a)}}form.onsubmit=e=>{e.preventDefault();const d=new FormData(form);const datetime=new Date(d.get("date")+"T"+d.get("time"));if(Number.isNaN(datetime.valueOf())||datetime<Date.now())return notify("Escolha data e horário futuros.");const entry={id:crypto.randomUUID(),nick:safe(d.get("nick")).slice(0,30),date:d.get("date"),time:d.get("time"),count:Number(d.get("count"))};const all=read("t48Reservations");if(all.some(x=>x.date===entry.date&&x.time===entry.time&&x.nick===entry.nick))return notify("Solicitação duplicada neste navegador.");write("t48Reservations",[entry,...all].slice(0,30));log("Reserva de teste criada");form.reset();draw();notify("Reserva demonstrativa salva neste navegador.")};draw()})}
function initReorder(){panel("pedir-novamente","Confira os preços antes de finalizar. Este botão usa o histórico do navegador e não envia pedidos à API.",root=>{const orders=read("trattoritoPedidos");if(!orders.length)return root.append(node("p","t48-muted","Nenhum pedido disponível neste navegador."));for(const o of orders.slice(0,8)){const c=row(o.id||"Pedido",fmt(o.total));const b=node("button","t48-small","Repetir no carrinho");b.onclick=()=>{const its=Array.isArray(o.items)?o.items:[];if(!its.length)return notify("Este registro não possui itens para repetir.");const cart=read("carrinhoCantina");for(const it of its){const n=safe(it.nome||it.nomeProduto||it.NomeProduto),p=Number(it.preco??it.precoUnitario??it.PrecoUnitario);if(!n||!Number.isFinite(p)||p<=0)continue;const x=cart.find(c=>c.nome===n&&!c.observacao);const q=Math.min(20,Math.max(1,Math.floor(Number(it.quantidade)||1)));if(x)x.quantidade=Number(x.quantidade||0)+q;else cart.push({nome:n,preco:p,quantidade:q,imagem:it.imagem||"",observacao:"",adicionais:""})}write("carrinhoCantina",cart);log("Repetir pedido de demonstração");notify("Itens enviados ao carrinho. Confira antes de finalizar.")};c.append(b);root.append(c)}})}
function initKitchen(){panel("cozinha","As comandas abaixo são apenas pedidos gravados pelo navegador. Não atualizam status no SQL Server.",root=>{const list=node("div","t48-list");root.append(list);function draw(){list.replaceChildren();const orders=[...read("t48PDV"),...read("trattoritoPedidos")].slice(0,14);if(!orders.length)list.append(node("p","t48-muted","Não há pedidos de demonstração neste navegador."));orders.forEach(o=>{const box=node("div","t48-mini");box.append(node("strong","",o.id||"Pedido"),node("small","",fmt(o.total)+" · "+safe(o.status||"recebido")));const created=new Date(o.date||o.createdAt||Date.now());const minutes=Math.max(0,Math.floor((Date.now()-created.getTime())/60000));box.append(node("small","",Number.isFinite(minutes)?"Há aproximadamente "+minutes+" min":"Tempo indisponível"));const btn=node("button","t48-small","Imprimir comanda");btn.onclick=()=>printMode("COMANDA DEMONSTRATIVA",[[o.id||"Pedido",""],["Total",fmt(o.total)],...((o.items||[]).slice(0,20).map(x=>[String(x.quantidade||1)+"x "+safe(x.nome||x.nomeProduto),fmt((Number(x.preco)||Number(x.precoUnitario)||0)*(Number(x.quantidade)||1))]))]);box.append(btn);list.append(box)})}draw();const update=node("button","t48-small","Atualizar cronômetro");update.onclick=draw;root.prepend(update)})}
function initStock(){panel("estoque","A disponibilidade só aparece neste painel de teste; não bloqueia vendas nem altera dbo.Produtos.",root=>{const list=node("div","t48-list");root.append(list);const draw=()=>{list.replaceChildren();const stock=read("t48Stock",{});for(const p of products){const checked=stock[p.n]!==false;const rowEl=node("label","t48-row t48-toggle");const title=node("span","",p.n);const input=document.createElement("input");input.type="checkbox";input.checked=checked;input.onchange=()=>{const current=read("t48Stock",{});current[p.n]=input.checked;write("t48Stock",current);log("Estoque de teste: "+p.n+(input.checked?" disponível":" esgotado"));notify("Estoque demonstrativo alterado.")};rowEl.append(title,input);list.append(rowEl)}};draw()})}
function initReports(){panel("relatorios","Dados obtidos de pedidos de demonstração salvos somente neste navegador.",root=>{const o=[...read("t48PDV"),...read("trattoritoPedidos")];const total=o.reduce((s,x)=>s+(Number(x.total)||0),0),count=o.length;const stats=node("div","t48-stats");stats.append(row("Pedidos registrados",String(count)),row("Soma demonstrativa",fmt(total)),row("Ticket médio",fmt(count?total/count:0)));root.append(stats);const top=new Map();for(const x of o)for(const it of (x.items||[])){const n=safe(it.nome||it.nomeProduto||"Item");top.set(n,(top.get(n)||0)+(Number(it.quantidade)||1))}const ordered=[...top].sort((a,b)=>b[1]-a[1]).slice(0,5);if(!ordered.length)root.append(node("p","t48-muted","Adicione um pedido de demonstração para ver o gráfico."));for(const [n,v] of ordered){const e=node("div","t48-bar");e.append(node("span","",n));const bar=node("div","t48-bar-track");const inner=node("span","");inner.style.width=Math.max(6,v/(ordered[0][1]||1)*100)+"%";bar.append(inner);e.append(bar,node("strong","",String(v)));root.append(e)}})}
function initHelp(){panel("assistente","Assistente com respostas programadas (não é IA nem atendimento humano).",root=>{const faq=[["Como consultar um pedido?","Use a aba Acompanhar pedido e o número recebido. No site público as informações de teste ficam neste navegador."],["Como personalizar um prato?","Abra o cardápio, clique em Personalizar, escolha quantidade e descreva observações para a cozinha."],["O pagamento é real?","Não. Este projeto usa pagamento demonstrativo. Não digite dados reais de cartão."],["A reserva está confirmada?","Não. Reservas nesta central são demonstrações locais e não chegam a um restaurante."],["Como entrar em minha conta?","Use Cadastro para criar um perfil demonstrativo e Entrar para acessar no mesmo navegador. Não use senhas pessoais."],["Como cancelar?","O cancelamento desta central altera apenas registros locais. A API SQL não é afetada."]];const form=makeForm("t48-helpform",'<label>Escolha sua dúvida<select name="question"></select></label><button type="submit">Ver resposta</button>');const select=$("select",form);options(select,faq.map((v,i)=>[String(i),v[0]]));const resp=node("div","t48-answer","Selecione uma dúvida e clique em Ver resposta.");form.onsubmit=e=>{e.preventDefault();resp.textContent=faq[Number(select.value)]?.[1]||"Pergunta não encontrada."};root.append(form,resp)})}
function initPWA(){panel("instalavel","No celular, use o menu do navegador e escolha Adicionar à tela inicial, quando disponível. O modo offline cobre apenas páginas e recursos estáticos, sem dados de pedidos ou perfis.",root=>{root.append(node("p","t48-muted","O manifest e o service worker funcionam em HTTPS. Fotos do cardápio usam carregamento tardio quando apropriado. A disponibilidade do botão Instalar depende do navegador."));const a=node("a","t48-btn","Voltar à página inicial");a.href="index.html";root.append(a)})}
function initAppearance(){panel("aparencia","Ative o tema escuro e aumente o tamanho da fonte desta central.",root=>{const dark=node("button","t48-btn",document.documentElement.dataset.t48Dark==="1"?"Desativar tema escuro":"Ativar tema escuro");dark.onclick=()=>{const active=document.documentElement.dataset.t48Dark==="1";document.documentElement.dataset.t48Dark=active?"0":"1";write("t48Dark",!active);dark.textContent=active?"Ativar tema escuro":"Desativar tema escuro"};const large=node("button","t48-btn","Alternar letras maiores");large.onclick=()=>{document.documentElement.classList.toggle("t48-large");write("t48Large",document.documentElement.classList.contains("t48-large"))};root.append(dark,large,node("p","t48-muted","Também incluímos atalho para pular ao conteúdo e foco visível para navegação por teclado."))})}
function initNotifications(){panel("notificacoes","Avisos internos deste navegador. Não são push notifications do restaurante.",root=>{const draw=()=>{const list=by("t48-notification-list");list.replaceChildren();const data=read("t48Notifications");for(const x of data.slice(0,12))list.append(row(new Date(x.date).toLocaleString("pt-BR"),x.text));if(!data.length)list.append(node("p","t48-muted","Nenhum aviso demonstrativo."))};const btn=node("button","t48-btn","Criar aviso de teste");btn.onclick=()=>{write("t48Notifications",[{date:new Date().toISOString(),text:"Seu aviso demonstrativo foi criado."},...read("t48Notifications")].slice(0,20));draw();notify("Aviso demonstrativo registrado.")};const list=node("div","t48-list");list.id="t48-notification-list";root.append(btn,list);draw()})}
function initPromos(){panel("promocoes","Pratos indicativos; estas ofertas não alteram o carrinho nem têm descontos validados pelo servidor.",root=>{const now=new Date(),name=products[now.getDay()%4];root.append(row("Sugestão do dia",name.n+" · "+fmt(name.p)),node("p","t48-muted","Menu sazonal ilustrativo: sabores de outono, pratos com funghi e massas da casa."));const form=makeForm("t48-promoform",'<label>Nome da promoção de teste<input name="title" maxlength="40" required placeholder="Ex.: Festival de massas"></label><label>Data de início<input name="start" type="date" required></label><label>Data final<input name="end" type="date" required></label><button type="submit">Agendar promoção visual</button>');root.append(form);const list=node("div","t48-list");root.append(list);const draw=()=>{list.replaceChildren();for(const x of read("t48Promotions").slice(0,8))list.append(row(x.title,x.start+" até "+x.end))};form.onsubmit=e=>{e.preventDefault();const d=new FormData(form);if(d.get("end")<d.get("start"))return notify("Fim anterior ao início.");write("t48Promotions",[{title:safe(d.get("title")),start:d.get("start"),end:d.get("end")},...read("t48Promotions")].slice(0,12));log("Promoção visual programada");form.reset();draw();notify("Promoção visual salva neste navegador.")};draw()})}
function initQR(){panel("qrcode","O QR Code aponta para o cardápio público. A imagem é gerada por um serviço externo usando apenas a URL pública do site.",root=>{const url="https://kayquejesusduarte1-a11y.github.io/trattorito/pratos.html";const image=node("img","t48-qr");image.src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data="+encodeURIComponent(url);image.width=220;image.height=220;image.alt="QR Code para abrir o cardápio público";image.loading="lazy";const a=node("a","t48-btn","Abrir cardápio");a.href=url;a.target="_blank";a.rel="noopener noreferrer";root.append(image,a,node("p","t48-muted",url))})}
function initFood(){panel("informacoes","As descrições são extraídas de apresentações do cardápio e NÃO constituem ficha técnica de alérgenos. Nunca presuma ausência de leite, glúten, ovos ou contaminação cruzada.",root=>{for(const p of products)root.append(row(p.n,p.ing));root.append(node("p","t48-disclaimer","Para qualquer restrição alimentar, confirme ingredientes, preparo e contaminação cruzada diretamente com um responsável pela cozinha."))})}
function initCompare(){panel("comparador","Selecione dois itens para visualizar preço e ingredientes conhecidos.",root=>{const form=makeForm("t48-compareform",'<label>Primeiro prato<select id="t48-comp1"></select></label><label>Segundo prato<select id="t48-comp2"></select></label><button type="submit">Comparar</button>');for(const id of ["t48-comp1","t48-comp2"])options(byPlaceholder(form,id),products.map((p,i)=>[String(i),p.n]));function byPlaceholder(f,id){return $("#"+id,f)}$("#t48-comp2",form).value="1";const box=node("div","t48-list");form.onsubmit=e=>{e.preventDefault();box.replaceChildren();for(const id of ["t48-comp1","t48-comp2"]){const p=products[Number(by(id).value)];if(p)box.append(row(p.n,fmt(p.p)+" · "+p.ing))}};root.append(form,box);form.dispatchEvent(new Event("submit",{cancelable:true}))})}
function initBuilder(){panel("montar-prato","Use um prato já cadastrado no cardápio: observações são anexadas ao item, sem criar produto nem aumentar preço.",root=>{const form=makeForm("t48-builder",'<label>Prato base<select name="item"></select></label><label>Preparação<select name="preparo"><option value="">Padrão</option><option>Molho separado</option><option>Sem molho extra</option><option>Sem queijo, se possível</option></select></label><label>Observações<textarea name="note" maxlength="110" placeholder="Observação para teste"></textarea></label><label>Quantidade<input name="qty" type="number" min="1" max="10" value="1" required></label><button type="submit">Adicionar ao carrinho</button>');options($('[name="item"]',form),products.map((p,i)=>[String(i),p.n]));form.onsubmit=e=>{e.preventDefault();const d=new FormData(form),p=products[Number(d.get("item"))];if(!p)return;const items=read("carrinhoCantina"),qty=Math.min(10,Math.max(1,Number(d.get("qty"))||1));const obs=[d.get("preparo"),safe(d.get("note"))].filter(Boolean).join(" · ").slice(0,180);let x=items.find(x=>x.nome===p.n&&x.observacao===obs&&!x.adicionais);if(x)x.quantidade=(Number(x.quantidade)||0)+qty;else items.push({nome:p.n,preco:p.p,quantidade:qty,imagem:p.img,observacao:obs,adicionais:""});write("carrinhoCantina",items);log("Prato personalizado no carrinho");notify("Prato cadastrado no carrinho. Confira no checkout.")};root.append(form)})}
function initSchedule(){panel("agendamentos","Agendar aqui NÃO reserva preparo ou entrega. Apenas registra uma preferência de teste.",root=>{const f=makeForm("t48-schedule",'<label>Data preferida<input name="date" type="date" required></label><label>Hora preferida<input name="time" type="time" required></label><label>Modalidade<select name="method"><option>Retirada</option><option>Entrega demonstrativa</option></select></label><button type="submit">Salvar preferência local</button>');const out=node("p","t48-muted","Nenhum agendamento de teste.");const draw=()=>{const a=read("t48Schedule",null);out.textContent=a?"Preferência local: "+a.date+" às "+a.time+" · "+a.method:"Nenhum agendamento de teste."};f.onsubmit=e=>{e.preventDefault();const d=new FormData(f);if(new Date(d.get("date")+"T"+d.get("time"))<new Date())return notify("Escolha um horário futuro.");write("t48Schedule",{date:d.get("date"),time:d.get("time"),method:d.get("method")});log("Agendamento ilustrativo");draw();notify("Preferência salva no navegador.")};root.append(f,out);draw()})}
function initReceipt(){panel("comprovante","Imprime o resumo de um pedido salvo neste navegador. No diálogo de impressão, escolha Salvar como PDF.",root=>{const orders=[...read("t48PDV"),...read("trattoritoPedidos")];const sel=document.createElement("select");options(sel,orders.map((o,i)=>[String(i),String(o.id||"Pedido")+" · "+fmt(o.total)]));const b=node("button","t48-btn","Imprimir / Salvar PDF");b.disabled=!orders.length;b.onclick=()=>{const o=orders[Number(sel.value)];if(!o)return;const lines=[[String(o.id||"Pedido"),new Date(o.date||o.createdAt||Date.now()).toLocaleString("pt-BR")],...((o.items||[]).map(x=>[String(x.quantidade||1)+"x "+safe(x.nome||x.nomeProduto||"Produto"),fmt((Number(x.preco)||Number(x.precoUnitario)||0)*(Number(x.quantidade)||1))])),["Total demonstrativo",fmt(o.total)]];printMode("COMPROVANTE DE PEDIDO DEMONSTRATIVO",lines)};root.append(sel,b);if(!orders.length)root.append(node("p","t48-muted","Sem pedidos no navegador para imprimir."))})}
function initPDV(){panel("pdv","PDV demonstrativo. Não realiza cobranças, nem grava no SQL Server.",root=>{const f=makeForm("t48-pdvform",'<label>Produto<select name="item"></select></label><label>Quantidade<input name="qty" type="number" value="1" min="1" max="20" required></label><button type="submit">Criar pedido de caixa local</button>');options($('[name="item"]',f),products.map((p,i)=>[String(i),p.n+" · "+fmt(p.p)]));const list=node("div","t48-list");const draw=()=>{list.replaceChildren();for(const o of read("t48PDV").slice(0,9))list.append(row(o.id,o.items[0].quantidade+"x "+o.items[0].nome+" · "+fmt(o.total)))};f.onsubmit=e=>{e.preventDefault();const d=new FormData(f),p=products[Number(d.get("item"))],q=Number(d.get("qty"));if(!p||!Number.isInteger(q)||q<1||q>20)return;const n=Date.now().toString(36).toUpperCase(),entry={id:"PDV-DEMO-"+n,date:new Date().toISOString(),status:"recebido",items:[{nome:p.n,quantidade:q,preco:p.p}],total:Math.round(p.p*q*100)/100};write("t48PDV",[entry,...read("t48PDV")].slice(0,40));log("Pedido PDV demonstrativo criado");draw();notify("Pedido de caixa local criado. Não chegou ao SQL Server.")};root.append(f,list);draw()})}
function initOpen(){panel("funcionamento","A opção altera apenas um indicador na central; os horários e o checkout reais não são afetados.",root=>{const status=node("h3","","");const toggle=node("button","t48-btn","");function draw(){const on=read("t48Open",true);status.textContent=on?"🟢 Aberto — simulação local":"🔴 Fechado — simulação local";toggle.textContent=on?"Simular fechamento":"Simular abertura"}toggle.onclick=()=>{write("t48Open",!read("t48Open",true));log("Funcionamento local alternado");draw()};root.append(status,toggle);draw()})}
function initCancel(){panel("cancelamentos","O botão modifica apenas o histórico local de demonstração. Não pode cancelar pedidos do SQL Server.",root=>{const sel=document.createElement("select");const orders=read("trattoritoPedidos").filter(x=>x.status!=="cancelado");options(sel,orders.map((o,i)=>[String(i),String(o.id)+" · "+fmt(o.total)]));const b=node("button","t48-btn","Cancelar somente demonstração");b.disabled=!orders.length;b.onclick=()=>{const o=orders[Number(sel.value)];if(!o||!confirm("Cancelar apenas este registro local? O SQL Server NÃO será alterado."))return;const all=read("trattoritoPedidos");const item=all.find(x=>x.id===o.id);if(item){item.status="cancelado";write("trattoritoPedidos",all);log("Cancelamento de registro local "+o.id);notify("Registro local alterado. Servidor não atualizado.");b.disabled=true}};root.append(sel,b);if(!orders.length)root.append(node("p","t48-muted","Nenhum pedido de teste elegível no navegador."))})}
function initAudit(){panel("historico","Auditoria apenas das ações deste navegador. Uma auditoria verdadeira deve ser registrada no backend com autenticação.",root=>{const list=node("div","t48-list");root.append(list);const draw=()=>{list.replaceChildren();const items=read("t48Audit");if(!items.length)list.append(node("p","t48-muted","Nenhuma alteração de teste registrada."));for(const e of items.slice(0,30))list.append(row(new Date(e.date).toLocaleString("pt-BR"),e.action))};const b=node("button","t48-small","Atualizar histórico");b.onclick=draw;root.prepend(b);draw()})}
function initDelivery(){panel("entregas","Atribuições criadas aqui não são reais e não exibem dados de localização.",root=>{const f=makeForm("t48-deliveryform",'<label>Pedido de teste<input name="id" required maxlength="40" placeholder="Ex.: DEMO-100"></label><label>Entregador fictício<input name="driver" required maxlength="40" placeholder="Ex.: Entregador A"></label><button type="submit">Registrar atribuição local</button>');const list=node("div","t48-list");const draw=()=>{list.replaceChildren();for(const x of read("t48Delivery"))list.append(row(x.id,x.driver+" · atribuição de teste"))};f.onsubmit=e=>{e.preventDefault();const d=new FormData(f);write("t48Delivery",[{id:safe(d.get("id")),driver:safe(d.get("driver"))},...read("t48Delivery")].slice(0,30));log("Atribuição de entrega ilustrativa");f.reset();draw();notify("Atribuição demonstrativa registrada.")};root.append(f,list);draw()})}
function initQueue(){panel("fila","Gere senhas sem coletar nome completo ou contato.",root=>{const b=node("button","t48-btn","Gerar senha de espera");const list=node("div","t48-list");const draw=()=>{list.replaceChildren();for(const x of read("t48Queue")){const r=row("Senha "+x.n,x.status);if(x.status==="Aguardando"){const c=node("button","t48-small","Chamar");c.onclick=()=>{const a=read("t48Queue"),e=a.find(v=>v.n===x.n);if(e)e.status="Chamado";write("t48Queue",a);log("Senha "+x.n+" chamada");draw()};r.append(c)}list.append(r)}};b.onclick=()=>{const prev=read("t48Queue");const num=prev.reduce((m,v)=>Math.max(m,v.n),0)+1;write("t48Queue",[...prev,{n:num,status:"Aguardando"}].slice(-40));log("Senha de espera gerada");draw()};root.append(b,list);draw()})}
function initEvents(){panel("eventos","Solicitações apenas ilustrativas. Evite dados pessoais: não pedimos telefone nem endereço.",root=>{const f=makeForm("t48-eventform",'<label>Tipo de evento<select name="type"><option>Festa</option><option>Encontro de equipe</option><option>Confraternização</option></select></label><label>Data<input name="date" type="date" required></label><label>Convidados<input name="count" type="number" min="1" max="200" value="20" required></label><button type="submit">Salvar solicitação demonstrativa</button>');const list=node("div","t48-list");const draw=()=>{list.replaceChildren();for(const x of read("t48Events"))list.append(row(x.type,x.date+" · "+x.count+" pessoas"))};f.onsubmit=e=>{e.preventDefault();const d=new FormData(f);if(d.get("date")<new Date().toISOString().slice(0,10))return notify("Escolha data futura.");write("t48Events",[{type:d.get("type"),date:d.get("date"),count:Number(d.get("count"))},...read("t48Events")].slice(0,20));log("Evento ilustrativo solicitado");f.reset();draw();notify("Solicitação de teste salva. Não enviada ao restaurante.")};root.append(f,list);draw()})}
function initLanguages(){panel("idiomas","Esta demonstração traduz os controles principais da central. Uma tradução integral de todas as páginas ainda será necessária.",root=>{const labels={pt:["Bem-vindo à central de recursos","Explorar funcionalidades"],en:["Welcome to the features center","Explore features"],it:["Benvenuto nel centro funzionalità","Esplora le funzioni"]};const sel=document.createElement("select");options(sel,[["pt","Português"],["en","English"],["it","Italiano"]]);const preview=node("div","t48-answer");function draw(){const s=labels[sel.value];preview.replaceChildren(node("h3","",s[0]),node("p","",s[1]))}sel.onchange=draw;root.append(sel,preview);draw()})}
function initGallery(){panel("galeria","Imagens dos pratos presentes no repositório.",root=>{const wrap=node("div","t48-gallery");for(const p of products.filter(x=>x.img)){const fig=node("figure","");const img=document.createElement("img");img.src=p.img;img.alt=p.n;img.loading="lazy";img.width=240;img.height=180;fig.append(img,node("figcaption","",p.n));wrap.append(fig)}root.append(wrap)})}
function initInfra(){panel("infra","Estes são os requisitos para colocar os recursos no ar com clientes reais:",root=>{const list=node("ul","t48-infra-list");for(const s of ["Backend hospedado com HTTPS; não expor o SQL Server Express do seu computador na internet.","Cadastro e login com autenticação no servidor, senhas protegidas, sessões seguras e política de privacidade.","Permissões verificadas no backend para funcionários, cozinha, entregadores e administração.","Reservas, estoque, cupons, entregas e cancelamentos persistidos em tabelas próprias e validados na API.","Pedidos com chave de idempotência validada no servidor para impedir compras duplicadas.","Backups automatizados do banco, testes de recuperação e logs de auditoria protegidos.","Revisar informações alimentares com equipe real antes de divulgar alegações de alérgenos.","Pagamentos reais apenas por provedor especializado; nunca armazenar cartão no navegador."]){list.append(node("li","",s))}root.append(list)})}
function bindModules(){initReservation();initReorder();initKitchen();initStock();initReports();initHelp();initPWA();initAppearance();initNotifications();initPromos();initQR();initFood();initCompare();initBuilder();initSchedule();initReceipt();initPDV();initOpen();initCancel();initAudit();initDelivery();initQueue();initEvents();initLanguages();initGallery();initInfra()}
function global(){try{if(read("t48Dark",false))document.documentElement.dataset.t48Dark="1";if(read("t48Large",false))document.documentElement.classList.add("t48-large")}catch{}const skip=node("a","t48-skip","Pular para o conteúdo");skip.href="#t48-main";document.body.prepend(skip);const anchor=$("main");if(anchor&&!anchor.id)anchor.id="t48-main";const link=node("a","t48-global-link","✨ 48 recursos");link.href="recursos.html";const header=$(".topbar .nav")||$(".elite-top nav")||$(".site-header")||$(".account-nav");if(header)header.append(link);if(location.protocol==="https:"&&"serviceWorker" in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{})}$$("img:not([loading])").forEach(img=>{if(!img.classList.contains("logo-art")&&!img.closest(".hero"))img.loading="lazy"})}
function init(){global();initPortal();initLab()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();