/* Trattoria D'Elite - central de recursos, sem acesso a contas ou servidores
 * Todos os pedidos, agendas, estoque e funções de equipe nesta página são DEMONSTRATIVOS.
 */
(() => {
"use strict";
const F=[[1,"Página inicial premium","Ativa","index.html"],[2,"Personalização de pratos","Demonstração","pratos.html"],[3,"Carrinho inteligente","Demonstração","carrinho.html"],[4,"Fidelidade","Demonstração","index.html"],[5,"Acompanhamento visual","Demonstração","pedido.html"],[6,"Versão mobile","Ativa","index.html"],[7,"Busca inteligente","Ativa","pratos.html"],[8,"Recomendações","Ativa","pratos.html"],[9,"Reserva de mesas","Demonstração","#reservas"],[10,"Pedir novamente","Demonstração","#pedidos"],[11,"Painel administrativo","Demonstração","painel.html"],[12,"Painel da cozinha","Demonstração","#gestao"],[13,"Controle de estoque","Demonstração","#gestao"],[14,"Relatórios e gráficos","Demonstração","#gestao"],[15,"Assistente virtual","Demonstração","#ajuda"],[16,"Aplicativo instalável (PWA)","Parcial","#tecnologia"],[17,"Modo claro e escuro","Ativa","#tecnologia"],[18,"Central de notificações","Demonstração","#gestao"],[19,"Perfil do cliente","Demonstração","perfil.html"],[20,"Avaliações com fotos","Parcial","avaliacoes.html"],[21,"Menu do dia","Demonstração","#menu-dia"],[22,"Promoções programadas","Demonstração","combos.html"],[23,"QR Code do cardápio","Parcial","#tecnologia"],[24,"Lista de ingredientes","Parcial","#cardapio-info"],[25,"Comparador de pratos","Ativa","#cardapio-info"],[26,"Acessibilidade","Parcial","index.html"],[27,"Monte seu próprio prato","Demonstração","#monte"],[28,"Agendar pedidos","Demonstração","#reservas"],[29,"Informações alimentares","Parcial","#cardapio-info"],[30,"Comprovante PDF","Ativa","#pedidos"],[31,"Caixa digital (PDV)","Demonstração","#gestao"],[32,"Sistema de funcionários","Servidor necessário","#seguranca"],[33,"Impressão de comandas","Demonstração","#gestao"],[34,"Cronômetro de preparo","Demonstração","#gestao"],[35,"Aberto ou fechado","Demonstração","#gestao"],[36,"Cancelamento de pedidos","Demonstração","#pedidos"],[37,"Central de ajuda","Ativa","#ajuda"],[38,"Cardápio sazonal","Demonstração","#menu-dia"],[39,"Histórico de alterações","Demonstração","#gestao"],[40,"Painel de entregadores","Demonstração","#gestao"],[41,"Lista de espera","Demonstração","#reservas"],[42,"Eventos e encomendas","Demonstração","#reservas"],[43,"Três idiomas","Parcial","#tecnologia"],[44,"Galeria do restaurante","Ativa","#galeria"],[45,"Site mais rápido","Parcial","index.html"],[46,"SEO para Google","Parcial","index.html"],[47,"Backup do sistema","Parcial","#tecnologia"],[48,"Proteção contra pedidos duplicados","Parcial","#seguranca"]];
const KEY="trattoria48.";
const $=id=>document.getElementById(id), q=(tag,cls,txt)=>{const x=document.createElement(tag);if(cls)x.className=cls;if(txt!==undefined)x.textContent=txt;return x};
const read=(key,fallback=[])=>{try{const a=JSON.parse(localStorage.getItem(key));return a===null?fallback:a}catch{return fallback}};
const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{flash("Sem espaço para salvar neste navegador.");return false}};
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const date=s=>{const d=new Date(s);return Number.isNaN(d.valueOf())?"Data indisponível":d.toLocaleString("pt-BR")};
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const products=[
{nome:"Pizza Margherita",preco:49.9,img:"imagens/pratos/pizza-margherita.webp",descricao:"Tomate, mozzarella, manjericão e azeite."},
{nome:"Spaghetti alla Carbonara",preco:49.9,img:"imagens/pratos/spaghetti-carbonara.webp",descricao:"Espaguete, ovos, queijo, pancetta e pimenta-do-reino."},
{nome:"Spaghetti alla Norma",preco:39.9,img:"imagens/pratos/spaghetti-norma.webp",descricao:"Molho de tomate, berinjela, ricota e manjericão."},
{nome:"Risoto de Funghi",preco:79.9,img:"imagens/pratos/risoto-funghi.webp",descricao:"Arroz cremoso com funghi e queijo."},
{nome:"Gnocchi alla Sorrentina",preco:38.9,img:"imagens/pratos/gnocchi-sorrentina.webp",descricao:"Nhoque, molho de tomate, manjericão e queijo gratinado."},
{nome:"Salada Caprese",preco:29.9,img:"imagens/pratos/salada-caprese.webp",descricao:"Tomate, mozzarella de búfala, manjericão e azeite."},
{nome:"Tiramisù",preco:32.9,img:"imagens/sobremesas/tiramisu.webp",descricao:"Mascarpone, café, biscoito e cacau."},
{nome:"Limonada",preco:19.99,img:"",descricao:"Limão e gelo."}
];
let deferredInstall=null;
function flash(m){const x=$("feedback");x.textContent=m;x.classList.add("show");clearTimeout(flash.tm);flash.tm=setTimeout(()=>x.classList.remove("show"),3500)}
function audit(message){const a=read(KEY+"audit",[]);a.unshift({message,time:new Date().toISOString()});save(KEY+"audit",a.slice(0,30))}
function orders(){const a=read("trattoritoPedidos",[]);return Array.isArray(a)?a.filter(x=>x&&typeof x.id==="string"):[]}
function renderFeatures(){const v=norm($("featureSearch").value),status=$("statusSearch").value;const root=$("featureGrid");root.replaceChildren();let count=0;for(const [number,name,state,link] of F){if(v&&!norm(name+" "+number).includes(v))continue;if(status!=="todos"&&state!==status)continue;count++;const article=q("article","hub-feature"),n=q("span","num",String(number).padStart(2,"0")+" / 48"),s=q("span","hub-status "+(state==="Ativa"?"live":state==="Servidor necessário"?"pending":""),state),h=q("h3","",name),a=q("a","",state==="Servidor necessário"?"Saiba o que falta →":"Abrir recurso →");a.href=link;article.append(n,s,h,a);root.append(article)}if(!count)root.append(q("p","","Nenhuma melhoria encontrada."))}
function addCart(item,qty=1,note=""){let a=read("carrinhoCantina",[]);if(!Array.isArray(a))a=[];a.push({nome:String(item.nome||"Produto").slice(0,150),preco:Number(item.preco)||0,imagem:item.img||item.imagem||"",quantidade:qty,observacao:note.slice(0,160),adicionais:""});if(save("carrinhoCantina",a))flash("Adicionado ao carrinho. Confira antes de finalizar.")}
function initBuild(){const form=$("buildForm");form.addEventListener("submit",e=>{e.preventDefault();const map={carbonara:products[1],norma:products[2],margherita:products[0]},p=map[$("baseDish").value],qty=Math.max(1,Math.min(10,Number($("buildQty").value)||1));if(!p)return;addCart(p,qty,$("buildNotes").value.trim());audit("Prato base adicionado ao carrinho demonstrativo")})}
function initCompare(){for(const id of ["compareA","compareB"]){const e=$(id);products.forEach((p,i)=>{const op=q("option","",p.nome);op.value=i;e.append(op)})}$("compareB").selectedIndex=1;$("compareBtn").onclick=()=>{const a=products[Number($("compareA").value)],b=products[Number($("compareB").value)];$("compareOut").textContent=a.nome+" — "+money(a.preco)+"\n"+a.descricao+"\n\n"+b.nome+" — "+money(b.preco)+"\n"+b.descricao+"\n\nDiferença de preço: "+money(Math.abs(a.preco-b.preco))+"\n\nIngredientes informativos; alérgenos não verificados."}}
function initOrders(){const s=$("orderSelect");const all=orders();s.replaceChildren();if(!all.length){const op=q("option","","Nenhum pedido salvo neste navegador");op.value="";s.append(op);for(const b of ["repeatOrder","printReceipt","cancelOrder"])$(b).disabled=true;return}for(const o of all){const op=q("option","",o.id+" · "+money(o.total));op.value=o.id;s.append(op)}function selected(){return orders().find(o=>o.id===s.value)}function draw(){const o=selected();$("orderPreview").textContent=o?"Pedido "+o.id+"\nStatus local: "+(o.status||"recebido")+"\nTotal: "+money(o.total)+"\nItens: "+(o.items||[]).map(x=>(x.quantidade||1)+"x "+(x.nome||"Item")).join(", "):"Nenhum pedido."}s.onchange=draw;draw();$("repeatOrder").onclick=()=>{const o=selected();if(!o||!Array.isArray(o.items)||!o.items.length)return flash("Este pedido não possui itens disponíveis.");for(const i of o.items.slice(0,30)){const qty=Math.max(1,Math.min(20,Number(i.quantidade)||1));addCart({nome:i.nome,preco:i.preco??i.precoUnitario??0,imagem:""},qty,String(i.observacao||""))}audit("Itens de pedido local copiados para o carrinho");flash("Itens copiados. Confirme preços e disponibilidade antes de continuar.")};$("cancelOrder").onclick=()=>{const o=selected();if(!o)return;if(!confirm("Simular cancelamento somente neste navegador? Isso NÃO cancela o pedido na API ou em qualquer restaurante."))return;const c=read(KEY+"cancels",[]);c.push({id:o.id,time:new Date().toISOString()});save(KEY+"cancels",c);audit("Solicitação ilustrativa de cancelamento salva");flash("Solicitação de cancelamento de TESTE salva; o pedido real não foi alterado.")};$("printReceipt").onclick=()=>{const o=selected();if(!o)return;const root=$("receipt");root.replaceChildren();root.append(q("h2","","TRATTORIA D'ELITE — COMPROVANTE DEMONSTRATIVO"),q("p","","Pedido: "+o.id+" | "+date(o.createdAt)),q("p","","Não é comprovante fiscal, recibo de pagamento ou venda real."));let total=0;for(const it of (o.items||[])){const qty=Number(it.quantidade)||1,price=Number(it.preco??it.precoUnitario)||0;root.append(q("p","",qty+" × "+String(it.nome||"Produto")+" — "+money(price*qty)));total+=qty*price}root.append(q("h2","","Total registrado no navegador: "+money(o.total??total)));document.body.classList.add("hub-print");window.print();setTimeout(()=>document.body.classList.remove("hub-print"),700)}}
function drawRequests(){const list=read(KEY+"requests",[]);const root=$("requestsList");root.replaceChildren();if(!list.length)root.append(q("p","","Nenhuma solicitação de teste."));for(const r of list.slice().reverse().slice(0,30)){const item=q("div","hub-row");item.append(q("span","",r.type+" · "+r.name+" · "+r.date+" "+r.time+" · "+r.people+" pessoa(s)/unidade(s)"));root.append(item)}}
function initRequests(){const today=new Date().toISOString().slice(0,10);$("reqDate").min=today;$("requestForm").addEventListener("submit",e=>{e.preventDefault();const name=$("reqName").value.trim().slice(0,40),d=$("reqDate").value,t=$("reqTime").value,num=Math.max(1,Math.min(50,Number($("reqPeople").value)||1));if(!name||!d||!t||d<today)return flash("Informe um apelido, data futura ou atual e horário.");const r=read(KEY+"requests",[]);r.push({type:$("reqType").selectedOptions[0].textContent,name,date:d,time:t,people:num});save(KEY+"requests",r.slice(-50));audit("Solicitação de teste criada");drawRequests();$("requestForm").reset();flash("Solicitação salva somente neste navegador. NÃO é uma reserva confirmada.")});$("clearRequests").onclick=()=>{if(!confirm("Apagar as solicitações demonstrativas deste navegador?"))return;save(KEY+"requests",[]);drawRequests()};drawRequests()}
function loadTickets(){return read(KEY+"tickets",[])}
function saveTickets(data){save(KEY+"tickets",data);drawManagement()}
function drawManagement(){const root=$("tickets"),tickets=loadTickets();root.replaceChildren();if(!tickets.length)root.append(q("p","","Nenhuma comanda demonstrativa."));for(const t of tickets.slice().reverse().slice(0,25)){const item=q("div","hub-row");const secs=Math.max(0,Math.floor((Date.now()-new Date(t.createdAt).getTime())/1000));item.append(q("span","","#"+t.id.slice(0,6)+" · "+t.qty+"× "+t.item+" · "+Math.floor(secs/60)+" min · "+t.status));const b=q("button","hub-button",t.status==="preparo"?"Concluir":t.status==="recebido"?"Preparar":"Imprimir");b.type="button";b.onclick=()=>{const current=loadTickets(),found=current.find(x=>x.id===t.id);if(!found)return;if(found.status==="concluído"){const receipt=$("receipt");receipt.replaceChildren();receipt.append(q("h2","","COMANDA DE DEMONSTRAÇÃO"),q("p","","Nº "+found.id+" | "+found.qty+"x "+found.item),q("p","","Criado em "+date(found.createdAt)+" · Valor "+money(found.price*found.qty)),q("p","","Não representa preparo ou venda real."));document.body.classList.add("hub-print");window.print();setTimeout(()=>document.body.classList.remove("hub-print"),700)}else{found.status=found.status==="recebido"?"preparo":"concluído";save(KEY+"tickets",current);audit("Comanda demonstrativa passou para "+found.status);drawManagement()}};item.append(b);root.append(item)}const stock=read(KEY+"stock",{});const st=$("stockList");st.replaceChildren();for(const p of products.slice(0,6)){const v=Number.isFinite(stock[p.nome])?stock[p.nome]:10;const item=q("div","hub-row");item.append(q("span","",p.nome+" · "+v+" unidade(s) ilustrativas"));const plus=q("button","hub-button","Repor +1");plus.onclick=()=>{const now=read(KEY+"stock",{});now[p.nome]=Math.min(999,(Number.isFinite(now[p.nome])?now[p.nome]:10)+1);save(KEY+"stock",now);audit("Reposição local de estoque: "+p.nome);drawManagement()};item.append(plus);st.append(item)}const ordersLocal=orders();const revenue=ordersLocal.reduce((s,x)=>s+(Number(x.total)||0),0);$("reports").textContent="Pedidos registrados neste navegador: "+ordersLocal.length+"\nValor demonstrativo acumulado: "+money(revenue)+"\nComandas de teste: "+tickets.length+"\nTotal de peças locais: "+tickets.reduce((s,x)=>s+x.qty,0);$("driverReport").textContent="Painel de entregas de teste\nComandas em preparo: "+tickets.filter(x=>x.status==="preparo").length+"\nComandas concluídas: "+tickets.filter(x=>x.status==="concluído").length+"\nNenhum entregador ou rota real é acompanhado.";const isOpen=read(KEY+"open",true);$("openValue").textContent=isOpen?"Indicador de teste: ABERTO":"Indicador de teste: FECHADO";const logroot=$("activityList");logroot.replaceChildren();const logs=read(KEY+"audit",[]);if(!logs.length)logroot.append(q("p","","Sem atividades de demonstração."));for(const x of logs.slice(0,15))logroot.append(q("div","hub-row",date(x.time)+" · "+x.message))}
function initManagement(){const sel=$("posProduct");for(let i=0;i<products.length;i++){const op=q("option","",products[i].nome+" · "+money(products[i].preco));op.value=i;sel.append(op)}$("posForm").addEventListener("submit",e=>{e.preventDefault();const p=products[Number(sel.value)],qty=Math.max(1,Math.min(20,Number($("posQty").value)||1));if(!p)return;const tickets=loadTickets();tickets.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),item:p.nome,qty,price:p.preco,status:"recebido",createdAt:new Date().toISOString()});save(KEY+"tickets",tickets.slice(-100));const stock=read(KEY+"stock",{});stock[p.nome]=Math.max(0,(Number.isFinite(stock[p.nome])?stock[p.nome]:10)-qty);save(KEY+"stock",stock);audit("Comanda de TESTE criada");drawManagement();flash("Comanda local criada. Nenhum pedido enviado à API.")});$("openStatus").onclick=()=>{save(KEY+"open",!read(KEY+"open",true));audit("Indicador local aberto/fechado alterado");drawManagement()};$("refreshLogs").onclick=drawManagement;drawManagement();setInterval(()=>{if(!document.hidden)drawManagement()},60000)}
function initHelp(){const ans={pedido:"Abra Acompanhar pedido. O site público mostra somente pedidos demonstrativos deste navegador. Pedidos da API local exigem seu servidor ligado.",conta:"Abra Cadastro, crie um perfil com dados fictícios e entre com um acesso de teste. Não use senhas pessoais. O perfil fica apenas neste navegador.",pagamento:"Não. O site é uma demonstração escolar. Não insira dados reais de cartão.",reserva:"Não. As solicitações desta central são simulações locais, sem confirmação de mesas ou horários.",alergia:"As descrições dos pratos não são fichas oficiais de alérgenos. Para restrições alimentares, consulte informações verificadas do estabelecimento.",offline:"O site contém configuração experimental de aplicativo instalável. O recurso depende da compatibilidade do navegador, HTTPS e arquivos em cache. O checkout exige conexão."};$("helpBtn").onclick=()=>$("helpAnswer").textContent=ans[$("helpTopic").value]||"Ajuda não disponível."}
function initTech(){const theme=localStorage.getItem(KEY+"theme")==="dark";document.body.classList.toggle("hub-night",theme);$("themeToggle").onclick=()=>{const on=document.body.classList.toggle("hub-night");localStorage.setItem(KEY+"theme",on?"dark":"light")};const words={pt:["Central D'Elite","Um espaço para conhecer as melhorias, explorar recursos úteis e experimentar as ferramentas demonstrativas do projeto."],en:["D'Elite Feature Hub","Explore improvements, useful tools and demonstration features in this school project."],it:["Centro D'Elite","Scopri miglioramenti, strumenti e funzioni dimostrative di questo progetto scolastico."]};$("langSelect").onchange=e=>{const [a,b]=words[e.target.value]||words.pt;$("hubTitle").textContent=a;$("hubIntro").textContent=b};$("backupLocal").onclick=()=>{const keys=["trattoritoPedidos","eliteFavoritos",KEY+"requests",KEY+"tickets",KEY+"audit",KEY+"stock",KEY+"cancels"];const data={kind:"trattoria-demonstracao",version:1,exportedAt:new Date().toISOString(),notes:"Não é backup de contas, API nem SQL Server",values:{}};for(const key of keys)data.values[key]=read(key,null);const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=q("a");link.href=url;link.download="trattoria-dados-demonstrativos.json";document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);audit("Backup de dados ilustrativos exportado");flash("Arquivo JSON demonstrativo exportado. Sem senhas.")};$("copyMenu").onclick=async()=>{const url=new URL("pratos.html",location.href).href;try{await navigator.clipboard.writeText(url);flash("Link do cardápio copiado.")}catch{flash("Copie o link: "+url)}};window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e});$("installPwa").onclick=async()=>{if(!deferredInstall){flash("Use a opção 'Instalar' no menu do navegador, se disponível.");return}deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null};if("serviceWorker" in navigator&&location.protocol==="https:")navigator.serviceWorker.register("sw.js").catch(()=>{})}
function init(){
 $("featureSearch").addEventListener("input",renderFeatures);$("statusSearch").addEventListener("change",renderFeatures);renderFeatures();initBuild();initCompare();initOrders();initRequests();initManagement();initHelp();initTech();
 const loc=document.getElementById("orderSelect");if(location.hash==="#pedidos"&&loc)loc.focus();
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();